import { useEffect, useState } from 'react'; import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { Activity, ArrowLeftRight, Boxes, ChevronRight, CircleDollarSign, FolderKanban, Fuel, Gauge, LayoutDashboard, LogOut, Menu, Network, Send, Settings, ShieldCheck, WalletCards, Zap } from 'lucide-react'; import { api } from './api';
const menu=[['控制台','/',LayoutDashboard],['钱包中心','/wallets',WalletCards],['批量钱包','/batch-wallets',Boxes],['批量转账','/batch-transfer',Send],['资产归集','/collection',CircleDollarSign],['闪电兑换','/swap',ArrowLeftRight],['GasFree','/gasfree',Fuel],['闪电贷款','/flash-loan',Zap],['项目中心','/projects',FolderKanban],['市场数据','/markets',Activity],['安全中心','/security',ShieldCheck],['系统设置','/settings',Settings]] as const;
function Shell(){const[open,setOpen]=useState(false);return <div className="app"><aside className={open?'open':''}><div className="brand"><span className="logo-mark">ϟ</span><div><b>闪电钱包</b><small>LIGHTNING WALLET</small></div></div><nav>{menu.map(([n,p,I])=><NavLink key={p} to={p} end={p==='/'} onClick={()=>setOpen(false)}><I size={18}/><span>{n}</span></NavLink>)}</nav><div className="sidebar-foot"><div className="system-dot"/>系统运行正常 <small>v1.0.0</small></div></aside><main className="content"><header><button className="menu" onClick={()=>setOpen(!open)}><Menu/></button><div className="crumb">运营中心 <ChevronRight size={14}/> 正式环境</div><div className="operator"><span>LW</span><div><b>运营管理员</b><small>安全会话</small></div><LogOut size={17}/></div></header><div className="page"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/batch-wallets" element={<BatchWallets/>}/><Route path="/flash-loan" element={<FlashLoan/>}/>{menu.slice(1).map(([n,p,I])=><Route key={p} path={p} element={<Module name={n} icon={<I/>}/>}/>) }<Route path="*" element={<Navigate to="/" replace/>}/></Routes></div></main></div>}
export function App(){const authenticated=Boolean(localStorage.getItem('lightning-session'));return <Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={authenticated?<Shell/>:<Navigate to="/login" replace/>}/></Routes>}
function Login(){const nav=useNavigate();const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const result=await api<{data:{token:string}}>('/auth/login',{method:'POST',body:JSON.stringify({email:data.get('email'),password:data.get('password')})});localStorage.setItem('lightning-session',result.data.token);nav('/')}catch{setError('登录失败，请检查账号、密码和 API 状态')}finally{setBusy(false)}}return <main className="login"><section><div className="login-brand"><span className="logo-mark">ϟ</span><b>闪电钱包</b></div><p className="eyebrow">SECURE OPERATOR ACCESS</p><h1>让链上运营<br/><em>快如闪电。</em></h1><p>一个入口，管理多链资产、批量任务与协议集成。</p></section><form onSubmit={submit}><h2>欢迎回来</h2><p>登录您的运营控制台</p><label>邮箱<input name="email" type="email" defaultValue="admin@lightning.local" required/></label><label>密码<input name="password" type="password" defaultValue="lightning-demo" minLength={8} required/></label>{error&&<div className="login-error">{error}</div>}<button disabled={busy}>{busy?'正在验证…':'安全登录'} <ChevronRight size={18}/></button><small>统一登录后可访问钱包与闪电贷应用。</small></form></main>}
function Dashboard(){return <><PageHead eyebrow="OVERVIEW" title="控制台" desc="跨链资产与运营任务，一目了然。" action="新建任务"/><div className="stats"><Stat label="资产总值" value="$128,450.32" trend="+8.4%"/><Stat label="托管钱包" value="128" trend="7 条链"/><Stat label="今日操作" value="46" trend="全部成功"/><Stat label="待处理提醒" value="2" trend="需要关注" alert/></div><div className="grid"><section className="panel portfolio"><div className="panel-head"><div><p className="eyebrow">PORTFOLIO</p><h3>资产趋势</h3></div><select><option>最近 30 天</option></select></div><div className="chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#73f3ce" stopOpacity=".32"/><stop offset="1" stopColor="#73f3ce" stopOpacity="0"/></linearGradient></defs><path d="M0 190 C80 180 100 120 175 145 S290 90 350 110 S470 35 530 78 S620 20 700 38 L700 220 L0 220Z" fill="url(#g)"/><path d="M0 190 C80 180 100 120 175 145 S290 90 350 110 S470 35 530 78 S620 20 700 38" fill="none" stroke="#73f3ce" strokeWidth="3"/></svg></div></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">NETWORKS</p><h3>网络状态</h3></div></div>{['Ethereum','Solana','TRON','BNB Chain'].map((n,i)=><div className="network" key={n}><span className={`chain c${i}`}>{n[0]}</span><div><b>{n}</b><small>{i===0?'12.4 Gwei':'运行正常'}</small></div><span className="online">在线</span></div>)}</section></div></>}
function PageHead({eyebrow,title,desc,action}:{eyebrow:string,title:string,desc:string,action?:string}){return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{desc}</p></div>{action&&<button><Zap size={17}/>{action}</button>}</div>}
function Stat({label,value,trend,alert}:{label:string,value:string,trend:string,alert?:boolean}){return <div className="stat"><div className="stat-icon"><Gauge size={19}/></div><span>{label}</span><strong>{value}</strong><small className={alert?'warn':''}>{trend}</small></div>}
function Module({name,icon}:{name:string,icon:React.ReactNode}){return <><PageHead eyebrow="LIGHTNING MODULE" title={name} desc={`${name}模块已接入统一权限、任务队列与审计边界。`}/><section className="panel empty"><div className="empty-icon">{icon}</div><h2>{name} 接口层已就绪</h2><p>业务适配器可以在不改变控制台结构的情况下接入。正式签名操作必须连接 HSM、MPC 或用户钱包。</p><button>查看集成说明</button></section></>}
function BatchWallets(){
  const [count,setCount]=useState(5);
  const [result,setResult]=useState<{address:string;label:string}[]>([]);
  const [busy,setBusy]=useState(false);
  async function run(){
    setBusy(true);
    try {
      const r=await api<{data:{address:string;label:string}[]}>('/wallets/batch-generate',{method:'POST',body:JSON.stringify({chain:'ethereum',count,labelPrefix:'运营钱包'})});
      setResult(r.data);
    } catch {
      setResult(Array.from({length:count},(_,i)=>({label:`预览钱包 ${i+1}`,address:`0x${String(i+1).padStart(40,'0')}`})));
    } finally { setBusy(false); }
  }
  return <><PageHead eyebrow="WALLET FACTORY" title="批量钱包" desc="生成、标记和安全导出多链钱包。"/><div className="grid"><section className="panel form-panel"><h3>创建钱包批次</h3><label>网络<select><option>Ethereum</option><option>Solana</option><option>TRON</option></select></label><label>数量<input type="number" min="1" max="100" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><div className="notice"><ShieldCheck size={18}/>生产环境必须将密钥交由 HSM 或 MPC 加密托管。</div><button onClick={run} disabled={busy}>{busy?'生成中…':'生成钱包'}</button></section><section className="panel"><div className="panel-head"><h3>生成结果</h3><span>{result.length} 个钱包</span></div>{result.length?<div className="wallet-list">{result.map(x=><div key={x.address}><b>{x.label}</b><code>{x.address}</code></div>)}</div>:<div className="mini-empty"><WalletCards/><p>尚未生成钱包</p></div>}</section></div></>;
}
function FlashLoan(){const url=import.meta.env.VITE_FLASH_LOAN_URL||'http://localhost:32104';const[status,setStatus]=useState<'checking'|'ready'|'offline'>('checking');useEffect(()=>{api<{data:{status:string}}>('/integrations/flash-loan/health').then(r=>setStatus(r.data.status==='ready'?'ready':'offline')).catch(()=>setStatus('offline'))},[]);return <><PageHead eyebrow="AAVE V3 · SEPOLIA" title="闪电贷款" desc="现有 FlashForge 程序已接入统一登录和控制台。主网交易保持关闭。"/><section className="panel integration"><div className="integration-icon"><Zap/></div><div><h2>FlashForge 测试网</h2><p>钱包连接由原程序通过同一浏览器钱包提供器完成，交易逻辑保持不变。</p><code>{url}</code></div><span className={`integration-status ${status}`}>{status==='checking'?'检查中':status==='ready'?'服务正常':'服务离线'}</span><a href={url} target="_blank" rel="noreferrer">独立打开 <ChevronRight size={18}/></a></section>{status==='ready'?<section className="flash-frame panel"><iframe title="FlashForge 闪电贷" src={url} allow="clipboard-read; clipboard-write"/><p>若钱包扩展不允许在嵌入页面连接，请使用“独立打开”。</p></section>:<section className="panel empty"><div className="empty-icon"><Zap/></div><h2>闪电贷服务暂时不可用</h2><p>主钱包其他页面不受影响。请确认 FlashForge 正在 {url} 运行后重试。</p><button onClick={()=>location.reload()}>重新检查</button></section>}</>}
