CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL DEFAULT 'operator', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS wallets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), chain text NOT NULL, address text NOT NULL, label text NOT NULL, encrypted_key_ref text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(chain,address));
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid REFERENCES users(id), name text NOT NULL, chain text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'draft', version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS project_versions (id bigserial PRIMARY KEY, project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, version integer NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,version));
CREATE TABLE IF NOT EXISTS project_deployments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, chain text NOT NULL, network text NOT NULL, contract_address text NOT NULL, transaction_hash text, status text NOT NULL, deployed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS operation_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, status text NOT NULL DEFAULT 'queued', idempotency_key text UNIQUE NOT NULL, payload jsonb NOT NULL, result jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id bigserial PRIMARY KEY, actor_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id text, ip inet, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_jobs_status_created ON operation_jobs(status,created_at); CREATE INDEX IF NOT EXISTS idx_audit_actor_created ON audit_logs(actor_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_projects_chain_status ON projects(chain,status); CREATE INDEX IF NOT EXISTS idx_project_versions_project ON project_versions(project_id,version DESC); CREATE INDEX IF NOT EXISTS idx_project_deployments_project ON project_deployments(project_id,deployed_at DESC);
