import bs58 from'bs58';import type{ScanInput,ScannedAsset}from'./types';import type{TransferChain}from'../batch-transfer/types';
const rpc={EVM:import.meta.env.VITE_EVM_RPC_URL||'https://ethereum-sepolia-rpc.publicnode.com',SOL:import.meta.env.VITE_SOLANA_RPC_URL||'https://api.devnet.solana.com',TRON:import.meta.env.VITE_TRON_RPC_URL||'https://nile.trongrid.io'};
const decimal=(raw:bigint,decimals:number)=>{const s=raw.toString().padStart(decimals+1,'0');return`${s.slice(0,-decimals)||'0'}.${s.slice(-decimals)}`.replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')};
async function json(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`RPC HTTP ${response.status}`);const data=await response.json();if(data.error)throw new Error(data.error.message??'RPC 返回错误');return data}
export async function scanAsset(chain:TransferChain,input:ScanInput,index:number):Promise<ScannedAsset>{const id=`${chain}-${index}-${input.address}`,asset=input.token?'token':'native';try{if(chain==='EVM'){const decimals=input.decimals??18,data=input.token?`0x70a08231000000000000000000000000${input.address.slice(2).toLowerCase()}`:undefined,balanceResult=await json(rpc.EVM,{jsonrpc:'2.0',id:index,method:input.token?'eth_call':'eth_getBalance',params:input.token?[{to:input.token,data},'latest']:[input.address,'latest']}),gasResult=await json(rpc.EVM,{jsonrpc:'2.0',id:index+10000,method:'eth_gasPrice',params:[]}),fee=BigInt(gasResult.result)*BigInt(input.token?65000:21000);return{...input,id,chain,asset,symbol:input.token?'ERC-20':'ETH',balance:decimal(BigInt(balanceResult.result),decimals),estimatedFee:decimal(fee,18),status:'ready'}}if(chain==='SOL'){if(input.token){const result=await json(rpc.SOL,{jsonrpc:'2.0',id:index,method:'getTokenAccountsByOwner',params:[input.address,{mint:input.token},{encoding:'jsonParsed'}]}),amount=(result.result.value as{account:{data:{parsed:{info:{tokenAmount:{uiAmountString:string}}}}}}[]).reduce((sum,item)=>sum+Number(item.account.data.parsed.info.tokenAmount.uiAmountString),0);return{...input,id,chain,asset,symbol:'SPL',balance:String(amount),estimatedFee:'0.00001',status:'ready'}}const result=await json(rpc.SOL,{jsonrpc:'2.0',id:index,method:'getBalance',params:[input.address]});return{...input,id,chain,asset,symbol:'SOL',balance:decimal(BigInt(result.result.value),9),estimatedFee:'0.000005',status:'ready'}}const addressHex=Array.from(bs58.decode(input.address).slice(0,21),b=>b.toString(16).padStart(2,'0')).join('');if(input.token){const parameter=addressHex.padStart(64,'0'),result=await json(`${rpc.TRON}/wallet/triggerconstantcontract`,{owner_address:input.address,contract_address:input.token,function_selector:'balanceOf(address)',parameter,visible:true}),raw=BigInt(`0x${result.constant_result?.[0]??'0'}`);return{...input,id,chain,asset,symbol:'TRC-20',balance:decimal(raw,input.decimals??6),estimatedFee:'15',status:'ready'}}const result=await json(`${rpc.TRON}/wallet/getaccount`,{address:input.address,visible:true});return{...input,id,chain,asset,symbol:'TRX',balance:decimal(BigInt(result.balance??0),6),estimatedFee:'1.1',status:'ready'}}catch(error){return{...input,id,chain,asset,symbol:input.token?'Token':'Native',balance:'0',estimatedFee:'0',status:'failed',error:error instanceof Error?error.message:'RPC 扫描失败'}}}

type ParsedSolanaAccount={account:{data:{parsed:{info:{mint:string;tokenAmount:{decimals:number;uiAmountString:string}}}}}};
async function discoverSolanaTokens(input:ScanInput,index:number):Promise<ScannedAsset[]>{
  const programs=['TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA','TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'];
  const responses=await Promise.all(programs.map((program,offset)=>json(rpc.SOL,{jsonrpc:'2.0',id:index+20_000+offset,method:'getTokenAccountsByOwner',params:[input.address,{programId:program},{encoding:'jsonParsed'}]})));
  const balances=new Map<string,{raw:number;decimals:number}>();
  for(const response of responses)for(const item of response.result.value as ParsedSolanaAccount[]){const info=item.account.data.parsed.info,current=balances.get(info.mint)??{raw:0,decimals:info.tokenAmount.decimals};balances.set(info.mint,{raw:current.raw+Number(info.tokenAmount.uiAmountString),decimals:info.tokenAmount.decimals})}
  return[...balances.entries()].filter(([,value])=>value.raw>0).map(([token,value],offset)=>({id:`SOL-${index}-token-${offset}-${input.address}`,chain:'SOL',asset:'token',symbol:`SPL·${token.slice(0,4)}`,address:input.address,token,decimals:value.decimals,balance:String(value.raw),estimatedFee:'0.00001',status:'ready'}));
}

export async function scanWalletAssets(chain:TransferChain,input:ScanInput,index:number):Promise<ScannedAsset[]>{
  if(input.token)return[await scanAsset(chain,input,index)];
  const native=await scanAsset(chain,input,index);
  if(chain!=='SOL'||native.status==='failed')return[native];
  try{return[native,...await discoverSolanaTokens(input,index)]}catch(error){return[native,{id:`SOL-${index}-tokens-${input.address}`,chain:'SOL',asset:'token',symbol:'SPL',address:input.address,balance:'0',estimatedFee:'0',status:'failed',error:error instanceof Error?`Token 扫描失败：${error.message}`:'Token 扫描失败'}]}
}
