import { createHash, createHmac } from 'node:crypto';
import { isIP } from 'node:net';
import { z } from 'zod';
import { config } from './config.js';
import type { Queryable } from './projects.js';
export const ruleKind=z.enum(['price','watchlist','portfolio','gas','health']);export const channelKind=z.enum(['telegram','email','webhook']);
const condition=z.object({chain:z.enum(['EVM','SOL','TRON']).optional(),address:z.string().max(120).optional(),metric:z.string().max(40).optional(),operator:z.enum(['above','below','change']).optional(),threshold:z.number().finite().optional(),target:z.string().max(200).optional()}).strict();
export const createRuleSchema=z.object({name:z.string().trim().min(2).max(80),kind:ruleKind,scheduleMinutes:z.number().int().min(1).max(10080),condition,channels:z.array(channelKind).max(3).default([])}).strict();
export const createChannelSchema=z.object({name:z.string().trim().min(2).max(80),kind:channelKind,destination:z.string().trim().min(3).max(500),enabled:z.boolean().default(false)}).strict();
export interface AutomationDb extends Queryable{}
export async function ensureAutomationSchema(db:AutomationDb){await db.query(`CREATE TABLE IF NOT EXISTS automation_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,kind text NOT NULL,enabled boolean NOT NULL DEFAULT true,schedule_minutes integer NOT NULL DEFAULT 15 CHECK(schedule_minutes BETWEEN 1 AND 10080),condition jsonb NOT NULL DEFAULT '{}',channels jsonb NOT NULL DEFAULT '[]',next_run_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS notification_channels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL,name text NOT NULL,destination text NOT NULL,enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS automation_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),rule_id uuid REFERENCES automation_rules(id) ON DELETE SET NULL,rule_name text NOT NULL,kind text NOT NULL,status text NOT NULL,attempt integer NOT NULL DEFAULT 1,dry_run boolean NOT NULL DEFAULT true,detail jsonb NOT NULL DEFAULT '{}',error text,created_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz);CREATE INDEX IF NOT EXISTS idx_automation_rules_due ON automation_rules(enabled,next_run_at);CREATE INDEX IF NOT EXISTS idx_automation_jobs_status_created ON automation_jobs(status,created_at DESC)`)}
export const publicChannel=(row:Record<string,unknown>)=>({...row,destination:maskDestination(String(row.destination??''),String(row.kind??''))});
export function maskDestination(value:string,kind:string){if(kind==='email'){const[a,b]=value.split('@');return a&&b?`${a.slice(0,2)}***@${b}`:'***'}if(kind==='telegram')return value.length>5?`${value.slice(0,3)}***${value.slice(-2)}`:'***';try{const url=new URL(value);return `${url.protocol}//${url.host}/***`}catch{return'***'}}
export function safeWebhook(value:string){try{const url=new URL(value);if(url.protocol!=='https:')return false;const host=url.hostname.toLowerCase();return isIP(host)===0&&!['localhost','metadata.google.internal'].includes(host)&&!host.endsWith('.local')}catch{return false}}
export function validateChannel(input:z.infer<typeof createChannelSchema>){if(input.kind==='email'&&!z.string().email().safeParse(input.destination).success)throw new Error('Invalid email destination');if(input.kind==='telegram'&&!/^-?\d{5,20}$/.test(input.destination))throw new Error('Invalid Telegram chat ID');if(input.kind==='webhook'&&!safeWebhook(input.destination))throw new Error('Webhook must be a public HTTPS URL');return input}
export async function createRule(db:AutomationDb,input:unknown){const value=createRuleSchema.parse(input),result=await db.query("INSERT INTO automation_rules(name,kind,schedule_minutes,condition,channels,next_run_at) VALUES($1,$2,$3::integer,$4,$5::jsonb,now()+($3::integer * interval '1 minute')) RETURNING *",[value.name,value.kind,value.scheduleMinutes,value.condition,JSON.stringify(value.channels)]);return result.rows[0]}
export async function executeRule(db:AutomationDb,id:string,attempt=1){z.string().uuid().parse(id);z.number().int().min(1).max(1000).parse(attempt);const rule=(await db.query('SELECT * FROM automation_rules WHERE id=$1',[id])).rows[0];if(!rule)throw new Error('Rule not found');const detail={monitoringOnly:true,condition:rule.condition,channels:rule.channels,message:`${rule.name} evaluated in read-only mode`,broadcast:false,serverSigning:false};const job=(await db.query("INSERT INTO automation_jobs(rule_id,rule_name,kind,status,attempt,dry_run,detail,finished_at) VALUES($1,$2,$3,'completed',$4,true,$5,now()) RETURNING *",[rule.id,rule.name,rule.kind,attempt,detail])).rows[0];await db.query("UPDATE automation_rules SET next_run_at=now()+(schedule_minutes * interval '1 minute'),updated_at=now() WHERE id=$1",[id]);return job}
export async function retryAutomationJob(db:AutomationDb,id:string){z.string().uuid().parse(id);const previous=(await db.query("SELECT rule_id,attempt FROM automation_jobs WHERE id=$1 AND status IN ('queued','failed')",[id])).rows[0];if(!previous?.rule_id)return null;return executeRule(db,String(previous.rule_id),Number(previous.attempt)+1)}
export async function runDueRules(db:AutomationDb){const due=await db.query('SELECT id FROM automation_rules WHERE enabled=true AND next_run_at<=now() ORDER BY next_run_at LIMIT 25');for(const row of due.rows)await executeRule(db,String(row.id));return due.rows.length}
export async function healthSnapshot(db:AutomationDb){const started=performance.now();await db.query('SELECT 1');return{status:'healthy',api:'online',postgres:'online',scheduler:'running',readOnlyDefault:true,latencyMs:Math.round(performance.now()-started),checkedAt:new Date().toISOString()}}
export const notificationSchema=z.object({channelId:z.string().uuid(),subject:z.string().trim().min(2).max(120),message:z.string().trim().min(1).max(2000),dryRun:z.boolean().default(true)}).strict();
async function post(url:string,body:unknown,headers:Record<string,string>={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body),signal:controller.signal});if(!response.ok)throw new Error(`Notification provider HTTP ${response.status}`)}finally{clearTimeout(timer)}}
async function recordNotificationJob(db:AutomationDb,row:Record<string,unknown>,value:z.infer<typeof notificationSchema>,delivered:boolean,dryRun:boolean){const destination=maskDestination(String(row.destination),String(row.kind)),detail={notificationOnly:true,channelId:String(row.id),channel:String(row.kind),destination,delivered,subjectHash:createHash('sha256').update(value.subject).digest('hex'),messageLength:value.message.length,broadcast:false,serverSigning:false};return(await db.query("INSERT INTO automation_jobs(rule_name,kind,status,attempt,dry_run,detail,finished_at) VALUES($1,'notification','completed',1,$2,$3,now()) RETURNING *",[`通知 · ${String(row.name)}`,dryRun,detail])).rows[0]}
export async function dispatchNotification(db:AutomationDb,input:unknown){const value=notificationSchema.parse(input),row=(await db.query('SELECT * FROM notification_channels WHERE id=$1',[value.channelId])).rows[0];if(!row)throw new Error('Channel not found');const kind=String(row.kind),destination=String(row.destination),masked=maskDestination(destination,kind);if(value.dryRun||!config.AUTOMATION_ENABLE_DELIVERY||!row.enabled){const job=await recordNotificationJob(db,row,value,false,true);return{status:'dry-run',delivered:false,channel:kind,destination:masked,jobId:job?.id}}if(kind==='telegram'){if(!config.TELEGRAM_BOT_TOKEN)throw new Error('Telegram provider is not configured');await post(`https://api.telegram.org/bot${config.TELEGRAM_BOT_TOKEN}/sendMessage`,{chat_id:destination,text:`${value.subject}\n${value.message}`})}else if(kind==='email'){if(!config.EMAIL_PROVIDER_URL||!config.EMAIL_API_KEY)throw new Error('Email provider is not configured');await post(config.EMAIL_PROVIDER_URL,{to:destination,subject:value.subject,text:value.message},{authorization:`Bearer ${config.EMAIL_API_KEY}`})}else if(kind==='webhook'){if(!safeWebhook(destination)||!config.WEBHOOK_SIGNING_SECRET)throw new Error('Webhook delivery is not configured');const body=JSON.stringify({subject:value.subject,message:value.message,source:'lightning-wallet'}),signature=createHmac('sha256',config.WEBHOOK_SIGNING_SECRET).update(body).digest('hex');await post(destination,JSON.parse(body),{'x-lightning-signature':signature})}else throw new Error('Unsupported notification channel');const job=await recordNotificationJob(db,row,value,true,false);return{status:'delivered',delivered:true,channel:kind,destination:masked,jobId:job?.id}}
