import{z}from'zod';import{operationId}from'./adapters.js';
const url=z.union([z.literal(''),z.string().url().refine(value=>/^https?:\/\//i.test(value),'Only HTTP(S) links are allowed')]);
const amount=z.string().regex(/^\d{1,78}$/);
const launchNetworks:Record<'EVM'|'SOL'|'TRON',ReadonlySet<string>>={EVM:new Set(['sepolia','ethereum','bsc','polygon','base','arbitrum']),SOL:new Set(['solana-devnet','solana-mainnet']),TRON:new Set(['tron-nile','tron-shasta','tron-mainnet'])};
export const launchpadDraftSchema=z.object({chain:z.enum(['EVM','SOL','TRON']),network:z.enum(['sepolia','ethereum','bsc','polygon','base','arbitrum','solana-devnet','solana-mainnet','tron-nile','tron-shasta','tron-mainnet']),name:z.string().trim().min(2).max(50),symbol:z.string().trim().toUpperCase().regex(/^[A-Z0-9]{2,12}$/),decimals:z.number().int().min(0).max(18),supply:amount,description:z.string().trim().max(1000),website:url,socials:z.object({x:url,telegram:url,discord:url}),media:z.object({logo:z.object({name:z.string().trim().min(1).max(120),type:z.enum(['image/png','image/jpeg','image/webp']),size:z.number().int().min(0).max(2_000_000)}).optional(),banner:z.object({name:z.string().trim().min(1).max(120),type:z.enum(['image/png','image/jpeg','image/webp']),size:z.number().int().min(0).max(5_000_000)}).optional(),whitepaper:z.object({name:z.string().trim().min(1).max(120),type:z.literal('application/pdf'),size:z.number().int().min(0).max(10_000_000)}).optional()}),liquidity:z.object({tokenAmount:amount,quoteSymbol:z.string().trim().toUpperCase().regex(/^[A-Z0-9]{2,12}$/),quoteAmount:amount,lockDays:z.number().int().min(0).max(3650)}),dryRun:z.boolean()}).superRefine((draft,ctx)=>{if(!launchNetworks[draft.chain].has(draft.network))ctx.addIssue({code:'custom',path:['network'],message:'Network does not match chain'});if(draft.chain==='SOL'&&draft.decimals>9)ctx.addIssue({code:'custom',path:['decimals'],message:'Solana decimals cannot exceed 9'});for(const[path,value]of[['supply',draft.supply],['liquidity.tokenAmount',draft.liquidity.tokenAmount],['liquidity.quoteAmount',draft.liquidity.quoteAmount]]as const)if(BigInt(value)===0n)ctx.addIssue({code:'custom',path:path.split('.'),message:'Amount must be positive'})});
export type LaunchpadDraft=z.infer<typeof launchpadDraftSchema>;
export function createDeploymentPlan(input:unknown){const draft=launchpadDraftSchema.parse(input);return{planId:operationId(),chain:draft.chain,network:draft.network,dryRun:draft.dryRun,status:draft.dryRun?'validated':'signature-required',broadcast:false,serverSigning:false,requiredSigner:'user-wallet',checklist:{token:true,metadata:Boolean(draft.description),logo:Boolean(draft.media.logo),banner:Boolean(draft.media.banner),links:Boolean(draft.website||draft.socials.x||draft.socials.telegram||draft.socials.discord),whitepaper:Boolean(draft.media.whitepaper),liquidity:BigInt(draft.liquidity.tokenAmount)>0n&&BigInt(draft.liquidity.quoteAmount)>0n}}}
export interface LaunchpadStore{query(text:string,values?:unknown[]):Promise<{rows:Record<string,unknown>[]}>}
export async function persistDeploymentPlan(db:LaunchpadStore,input:unknown){const draft=launchpadDraftSchema.parse(input),plan=createDeploymentPlan(draft),projectId=operationId(),projectStatus=draft.dryRun?'draft':'review',metadata={symbol:draft.symbol,description:draft.description,website:draft.website||undefined,socials:draft.socials,tokenStandard:{EVM:'ERC-20',SOL:'SPL Token',TRON:'TRC-20'}[draft.chain],decimals:draft.decimals,supply:draft.supply,network:draft.network,media:draft.media,liquidity:draft.liquidity,planId:plan.planId,dryRun:draft.dryRun},payload={projectId,chain:draft.chain,network:draft.network,symbol:draft.symbol,dryRun:draft.dryRun},result={validated:true,broadcast:false,serverSigning:false};await db.query("WITH created_project AS (INSERT INTO projects(id,name,chain,status,version,metadata) VALUES($1,$2,$3,$4,1,$5) RETURNING id),created_version AS (INSERT INTO project_versions(project_id,version,metadata,status) SELECT id,1,$5,$4 FROM created_project RETURNING project_id),created_job AS (INSERT INTO operation_jobs(id,kind,status,idempotency_key,payload,result) SELECT $6,'launchpad-plan',$7,id::text,$8,$9 FROM created_project RETURNING id) SELECT id FROM created_project",[projectId,draft.name,draft.chain,projectStatus,metadata,plan.planId,plan.status,payload,result]);return{...plan,projectId}}
