import{z}from'zod';
export const projectQuerySchema=z.object({q:z.string().trim().max(80).optional(),chain:z.enum(['EVM','SOL','TRON']).optional(),status:z.enum(['draft','review','approved','deployed','archived']).optional()});
export const projectIdSchema=z.string().uuid();
export interface Queryable{query(text:string,values?:unknown[]):Promise<{rows:Record<string,unknown>[]}>}
const httpUrl=z.string().url().refine(value=>/^https?:\/\//i.test(value));
function safeUrl(value:unknown){const parsed=httpUrl.safeParse(value);return parsed.success?parsed.data:undefined}
function safeText(value:unknown,max=500){return typeof value==='string'?value.slice(0,max):undefined}
export function publicMetadata(input:unknown){const value=input&&typeof input==='object'?input as Record<string,unknown>:{};const socials=value.socials&&typeof value.socials==='object'?value.socials as Record<string,unknown>:{};return{symbol:safeText(value.symbol,16),description:safeText(value.description,1000),logoUrl:safeUrl(value.logoUrl),bannerUrl:safeUrl(value.bannerUrl),website:safeUrl(value.website),whitepaperUrl:safeUrl(value.whitepaperUrl),socials:{x:safeUrl(socials.x),telegram:safeUrl(socials.telegram),discord:safeUrl(socials.discord)},tokenStandard:safeText(value.tokenStandard,40),decimals:typeof value.decimals==='number'?value.decimals:undefined,supply:safeText(value.supply,100)}}
export async function listProjects(db:Queryable,input:unknown){const query=projectQuerySchema.parse(input),conditions:string[]=[];const values:unknown[]=[];if(query.q){values.push(`%${query.q}%`);conditions.push(`(name ILIKE $${values.length} OR metadata->>'symbol' ILIKE $${values.length})`)}if(query.chain){values.push(query.chain);conditions.push(`chain = $${values.length}`)}if(query.status){values.push(query.status);conditions.push(`status = $${values.length}`)}const result=await db.query(`SELECT id,name,chain,status,version,metadata,created_at FROM projects ${conditions.length?`WHERE ${conditions.join(' AND ')}`:''} ORDER BY created_at DESC LIMIT 200`,values);return result.rows.map(row=>({...row,metadata:publicMetadata(row.metadata)}))}
export async function projectDetails(db:Queryable,id:string){projectIdSchema.parse(id);const [project,versions,deployments]=await Promise.all([db.query('SELECT id,name,chain,status,version,metadata,created_at FROM projects WHERE id=$1',[id]),db.query('SELECT version,status,metadata,created_at FROM project_versions WHERE project_id=$1 ORDER BY version DESC LIMIT 100',[id]),db.query('SELECT id,chain,network,contract_address,transaction_hash,status,deployed_at FROM project_deployments WHERE project_id=$1 ORDER BY deployed_at DESC LIMIT 100',[id])]);if(!project.rows[0])return null;return{...project.rows[0],metadata:publicMetadata(project.rows[0].metadata),versions:versions.rows.map(row=>({...row,metadata:publicMetadata(row.metadata)})),deployments:deployments.rows}}
