export type SwapChain='EVM'|'SOL'|'TRON';export interface SwapQuoteInput{chain:SwapChain;chainId?:number;sellToken:string;buyToken:string;sellAmount:string;taker:string;slippageBps:number}
export interface SwapCandidate{provider:string;amountIn:string;amountOut:string;minReceived:string;priceImpactPct:number;route:string[];allowanceTarget?:string;transaction?:unknown;raw:unknown}
export interface SwapProviderAvailability{chain:SwapChain;available:boolean;provider:string;reason?:string}
export function swapProviderAvailability(env:NodeJS.ProcessEnv=process.env):SwapProviderAvailability[]{return[
  {chain:'EVM',available:Boolean(env.ZEROX_API_KEY),provider:'0x',...(env.ZEROX_API_KEY?{}:{reason:'EVM 聚合报价服务尚未配置'})},
  {chain:'SOL',available:true,provider:'Jupiter'},
  {chain:'TRON',available:Boolean(env.TRON_SWAP_PROVIDER_URL),provider:'SunSwap adapter',...(env.TRON_SWAP_PROVIDER_URL?{}:{reason:'TRON 聚合报价服务尚未配置'})},
]}
const number=(value:unknown)=>Number(value??0);async function read(response:Response){const body=await response.json();if(!response.ok)throw new Error(body?.reason??body?.message??`Aggregator HTTP ${response.status}`);return body}
export async function fetchSwapCandidates(input:SwapQuoteInput){const candidates:SwapCandidate[]=[];if(input.chain==='EVM'){const key=process.env.ZEROX_API_KEY;if(!key)throw new Error('ZEROX_API_KEY 未配置');const query=new URLSearchParams({chainId:String(input.chainId??1),sellToken:input.sellToken,buyToken:input.buyToken,sellAmount:input.sellAmount,taker:input.taker,slippageBps:String(input.slippageBps)}),raw=await read(await fetch(`https://api.0x.org/swap/allowance-holder/quote?${query}`,{headers:{'0x-api-key':key,'0x-version':'v2'}}));candidates.push({provider:'0x',amountIn:raw.sellAmount,amountOut:raw.buyAmount,minReceived:raw.minBuyAmount??raw.buyAmount,priceImpactPct:number(raw.estimatedPriceImpact??0)*100,route:(raw.route?.fills??[]).map((x:{source?:string})=>x.source).filter(Boolean),allowanceTarget:raw.issues?.allowance?.spender??raw.allowanceTarget,transaction:raw.transaction,raw})}else if(input.chain==='SOL'){const query=new URLSearchParams({inputMint:input.sellToken,outputMint:input.buyToken,amount:input.sellAmount,slippageBps:String(input.slippageBps),restrictIntermediateTokens:'true'}),raw=await read(await fetch(`https://lite-api.jup.ag/swap/v1/quote?${query}`));candidates.push({provider:'Jupiter',amountIn:raw.inAmount,amountOut:raw.outAmount,minReceived:raw.otherAmountThreshold,priceImpactPct:number(raw.priceImpactPct)*100,route:(raw.routePlan??[]).map((x:{swapInfo?:{label?:string}})=>x.swapInfo?.label).filter(Boolean),raw})}else{const endpoint=process.env.TRON_SWAP_PROVIDER_URL;if(!endpoint)throw new Error('TRON_SWAP_PROVIDER_URL 未配置');const raw=await read(await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}));for(const item of raw.candidates??[raw])candidates.push({provider:item.provider??'SunSwap',amountIn:item.amountIn??input.sellAmount,amountOut:item.amountOut,minReceived:item.minReceived??item.amountOut,priceImpactPct:number(item.priceImpactPct),route:item.route??[input.sellToken,input.buyToken],transaction:item.transaction,raw:item})}const extra=(process.env.SWAP_PROVIDER_URLS??'').split(',').map(x=>x.trim()).filter(Boolean);for(const endpoint of extra){try{const raw=await read(await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}));for(const item of raw.candidates??[raw])candidates.push({provider:item.provider??new URL(endpoint).hostname,amountIn:item.amountIn??input.sellAmount,amountOut:item.amountOut,minReceived:item.minReceived??item.amountOut,priceImpactPct:number(item.priceImpactPct),route:item.route??[input.sellToken,input.buyToken],allowanceTarget:item.allowanceTarget,transaction:item.transaction,raw:item})}catch{continue}}if(!candidates.length)throw new Error('没有可用聚合报价');return candidates.sort((a,b)=>BigInt(b.amountOut)-BigInt(a.amountOut)>0n?1:-1)}
