FROM node:22-alpine AS build
WORKDIR /app
ARG VITE_API_URL=http://localhost:3001/api/v1
ARG VITE_FLASH_LOAN_URL=http://localhost:32104
ARG VITE_WALLETCONNECT_PROJECT_ID=
ARG VITE_EVM_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com
ARG VITE_EVM_RPC_FALLBACK_URLS=https://rpc.sepolia.org
ARG VITE_SOLANA_RPC_URL=https://api.devnet.solana.com
ARG VITE_LAUNCHPAD_SOLANA_RPC_URL=https://api.devnet.solana.com
ARG VITE_SOLANA_RPC_FALLBACK_URLS=https://solana-rpc.publicnode.com,https://solana.drpc.org
ARG VITE_SOLANA_NETWORK=devnet
ARG VITE_TRON_RPC_URL=https://nile.trongrid.io
ARG VITE_TRON_RPC_FALLBACK_URLS=
ARG VITE_ADMIN_URL=https://admin.lightingwallet.com/login
ARG VITE_MAINNET_EXECUTION_ENABLED=false
ARG VITE_MAINNET_MAX_BATCH_COUNT=1000
ARG VITE_ENABLE_MAINNET_SWAP=false
ARG VITE_ENABLE_MAINNET_LAUNCHPAD=false
ARG VITE_ENABLE_MAINNET_BRIDGE=false
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_FLASH_LOAN_URL=$VITE_FLASH_LOAN_URL
ENV VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID
ENV VITE_EVM_RPC_URL=$VITE_EVM_RPC_URL
ENV VITE_EVM_RPC_FALLBACK_URLS=$VITE_EVM_RPC_FALLBACK_URLS
ENV VITE_SOLANA_RPC_URL=$VITE_SOLANA_RPC_URL
ENV VITE_LAUNCHPAD_SOLANA_RPC_URL=$VITE_LAUNCHPAD_SOLANA_RPC_URL
ENV VITE_SOLANA_RPC_FALLBACK_URLS=$VITE_SOLANA_RPC_FALLBACK_URLS
ENV VITE_SOLANA_NETWORK=$VITE_SOLANA_NETWORK
ENV VITE_TRON_RPC_URL=$VITE_TRON_RPC_URL
ENV VITE_TRON_RPC_FALLBACK_URLS=$VITE_TRON_RPC_FALLBACK_URLS
ENV VITE_ADMIN_URL=$VITE_ADMIN_URL
ENV VITE_MAINNET_EXECUTION_ENABLED=$VITE_MAINNET_EXECUTION_ENABLED
ENV VITE_MAINNET_MAX_BATCH_COUNT=$VITE_MAINNET_MAX_BATCH_COUNT
ENV VITE_ENABLE_MAINNET_SWAP=$VITE_ENABLE_MAINNET_SWAP
ENV VITE_ENABLE_MAINNET_LAUNCHPAD=$VITE_ENABLE_MAINNET_LAUNCHPAD
ENV VITE_ENABLE_MAINNET_BRIDGE=$VITE_ENABLE_MAINNET_BRIDGE
COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/core/package.json packages/core/package.json
RUN npm ci
COPY tsconfig.base.json ./
COPY packages/core packages/core
COPY apps/web apps/web
RUN npm run build -w @lightning/core && npm run build -w @lightning/web
FROM nginx:1.27-alpine
COPY docker/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
EXPOSE 4173
HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD wget -qO- http://127.0.0.1:4173/healthz || exit 1
