import { Interface, parseEther, parseUnits } from 'ethers';
import { Buffer } from 'buffer';
import type { TransferTask } from './types';
import { assertMainnetCanaryTask, reserveMainnetCanaryExecution } from '../mainnet-canary';
type EvmProvider={request(args:{method:string;params?:unknown[]}):Promise<unknown>};
type TronWeb={fullNode?:{host?:string};trx:{sendTransaction(to:string,amount:number):Promise<{result:boolean;txid:string}>};contract():{at(address:string):Promise<{transfer(to:string,amount:string):{send():Promise<string>}}>}};
declare global{interface Window{ethereum?:EvmProvider;tronWeb?:TronWeb;solana?:{publicKey?:{toString():string};signAndSendTransaction(tx:unknown):Promise<{signature:string}>}}}
export async function executeTask(task:TransferTask):Promise<string>{
  if(!window.confirm(`确认签名第 ${task.row-1} 笔交易？\n${task.amount} → ${task.to}`))throw new Error('用户取消签名');
  if(task.chain==='EVM'){if(!window.ethereum)throw new Error('未检测到 EVM 钱包');const accounts=await window.ethereum.request({method:'eth_requestAccounts'}) as string[];if(!accounts.some(address=>address.toLowerCase()===task.from.toLowerCase()))throw new Error('当前钱包账户与 CSV 发送钱包不一致');const chainId=String(await window.ethereum.request({method:'eth_chainId'})),testnet=chainId==='0xaa36a7';if(!testnet){assertMainnetCanaryTask(task,chainId);reserveMainnetCanaryExecution()}let data:undefined|string,value='0x0';if(task.token){data=new Interface(['function transfer(address,uint256)']).encodeFunctionData('transfer',[task.to,parseUnits(task.amount,task.decimals??18)]);}else value=`0x${parseEther(task.amount).toString(16)}`;return String(await window.ethereum.request({method:'eth_sendTransaction',params:[{from:task.from,to:task.token??task.to,value,...(data?{data}:{})}]}))}
  if(task.chain==='TRON'){if(!window.tronWeb)throw new Error('未检测到 TRON 钱包');const host=String(window.tronWeb.fullNode?.host??'').toLowerCase(),testnet=/(nile|shasta)/i.test(host);if(!testnet){assertMainnetCanaryTask(task,host);reserveMainnetCanaryExecution()}if(task.token){const contract=await window.tronWeb.contract().at(task.token);return contract.transfer(task.to,parseUnits(task.amount,task.decimals??6).toString()).send()}const result=await window.tronWeb.trx.sendTransaction(task.to,Number(parseUnits(task.amount,6)));if(!result.result)throw new Error('TRON 钱包拒绝交易');return result.txid}
  if(!window.solana?.publicKey||!window.solana.signAndSendTransaction)throw new Error('未检测到 Solana 钱包');
  if(window.solana.publicKey.toString()!==task.from)throw new Error('请切换到本笔任务的 Solana 发送钱包');
  const {Connection,PublicKey,SystemProgram,Transaction,TransactionInstruction}=await import('@solana/web3.js');const network=import.meta.env.VITE_SOLANA_NETWORK||'devnet',connection=new Connection(import.meta.env.VITE_SOLANA_RPC_URL||'https://api.devnet.solana.com','confirmed');if(network==='mainnet-beta'){assertMainnetCanaryTask(task,network);reserveMainnetCanaryExecution()}const owner=new PublicKey(task.from),recipient=new PublicKey(task.to);const transaction=new Transaction();
  if(task.token){const mint=new PublicKey(task.token),tokenProgram=new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'),associatedProgram=new PublicKey('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL');const ata=(wallet:InstanceType<typeof PublicKey>)=>PublicKey.findProgramAddressSync([wallet.toBuffer(),tokenProgram.toBuffer(),mint.toBuffer()],associatedProgram)[0],source=ata(owner),destination=ata(recipient),mintInfo=await connection.getAccountInfo(mint);if(!mintInfo)throw new Error('找不到 SPL Token Mint');const decimals=task.decimals??mintInfo.data[44]!,amount=parseUnits(task.amount,decimals),amountBytes=new Uint8Array(8);new DataView(amountBytes.buffer).setBigUint64(0,amount,true);transaction.add(new TransactionInstruction({programId:associatedProgram,keys:[{pubkey:owner,isSigner:true,isWritable:true},{pubkey:destination,isSigner:false,isWritable:true},{pubkey:recipient,isSigner:false,isWritable:false},{pubkey:mint,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false},{pubkey:tokenProgram,isSigner:false,isWritable:false}],data:Buffer.from([1])}),new TransactionInstruction({programId:tokenProgram,keys:[{pubkey:source,isSigner:false,isWritable:true},{pubkey:mint,isSigner:false,isWritable:false},{pubkey:destination,isSigner:false,isWritable:true},{pubkey:owner,isSigner:true,isWritable:false}],data:Buffer.from([12,...amountBytes,decimals])}))}else transaction.add(SystemProgram.transfer({fromPubkey:owner,toPubkey:recipient,lamports:parseUnits(task.amount,9)}));
  const latest=await connection.getLatestBlockhash();transaction.recentBlockhash=latest.blockhash;transaction.feePayer=owner;return (await window.solana.signAndSendTransaction(transaction)).signature;
}
